### ISSUE TITLE
Geometric distortion in distantly-placed models

### ISSUE THREAD

**Issue by GestiomaArkaitz** [xeokit/xeokit-convert#63]
## Issue

User reports: I am exporting to XKT some IFCs that contain traffic signals that look good in the IFC, when loaded in the viewer they show some geometric distortions in some signals and not in others, I would like to know if someone has a solution or if they can clarify why occurs.

### With distortion

![image](https://user-images.githubusercontent.com/94356173/176159438-5d5c5be7-cd67-4069-bba8-532bf27cf57c.png)

### Without distortion

![image](https://user-images.githubusercontent.com/94356173/176159818-6479545a-4a19-44b7-bf9c-58252f11e1b4.png)

## Background

Models positioned far from the coordinate origin often have vertex coordinates that have a high value and therefore require double-precision to view accurately.

GPUs only support single-precision, however, which results in jittering.

To  work around this, we emulate double-precision coordinates by partitioning the coordinates into 3D rectilinear tiles, and make each coordinate's values relative to its tile's origin. This enables us to store them more efficiently, as single-precision values, and to use special math and shader tricks to view them as if they were double-precision.

* More info in this [xeokit tutorial](https://www.notion.so/xeokit/Viewing-Double-Precision-Models-3f9e155fd1394d1f974474484decf31b)

## Accuracy 

The accuracy of this scheme depends on selecting an appropriate tile size for the magnitude of the coordinates we wish to place into it (ie. partitioning). For small coordinates, we can choose a large tile size, since the density of available accurate floating-point values (IEEE 754) is greater at the lower end of the floating point range. As coordinate magnitudes increase, however, we must choose an increasingly smaller tile size, since the available accurate values become sparser at the higher end of the floating point range.

## Tasks

For a given set of coordinates, find a heuristic that automatically computes the optimal tile size, that would best preserve their accuracy when they are converted to RTC.     

As an interim step until we have such a robust heuristic, we'll start by setting xeokit's default tile size to ````1000````, which works nicely with some of our super-distant roadworks models. 

The more tiles we have, the slower the viewer, however, since each tile represents at least one WebGL draw call, so the heuristic is more desirable, since it would create the minimal number of tiles.

- [x] Set default RTC tile size to ````1000```` in ````convert2xkt```` and ````xeokit-sdk````
- [x] Add option to ````convert2xkt```` to specify a user-configured tile size
- [ ] Insert function into ````convert2xkt```` and ````xeokit-sdk```` to automatically compute optimal tile size for given coordinates

**Comment by xeolabs** [comment]
Now fixed in 

* xeokit-convert 1.1.0-alpha-10
* xeokit-sdk 2.3.0-beta-33
* xeokit-bim-viewer 2.4.7-beta-11

Fixed by having a default tile size of ````200```` in xeokit-convert. We'll change that to a calculated value later. Can reduce this value if inaccuracies persist in the meantime.
